### ISSUE TITLE
Scraping realtime crypto market price data using web crawler/API 

### ISSUE THREAD

**Issue by priyanshux** [priyanshux/cryptopy#1]
Use API or scrape data using DOM. Some of the following APIs may be helpful:
https://docs.coincap.io/
https://bittrex.github.io/api/v3
https://coinmarketcap.com/api/

**Comment by Divyansh-20** [comment]
@priyanshux Can this be assigned to me ?

**Comment by priyanshux** [comment]
@Divyansh-20 sure go ahead

**Comment by priyanshux** [comment]
note: multiple students can work on same issues

**Comment by ayushsurana710** [comment]
@priyanshux Can I work on this issue?

**Comment by priyanshux** [comment]
@ayushsurana710 yes sure, go ahead

**Comment by Fafnir841** [comment]
@priyanshux  I would like to work on this issue too.

**Comment by Fafnir841** [comment]
can we scrape data using Python's beautifulsoup4 and requests libraries???

**Comment by priyanshux** [comment]
@Fafnir841 this issue has almost been resolved by @Atharvat

**Comment by priyanshux** [comment]
@Fafnir841 we now need to use the returned data and store it on a hourly/daily basis, would you like to work on it? I will open up a new issue soon

**Comment by priyanshux** [comment]
@Divyansh-20 what's your status?

**Comment by priyanshux** [comment]
Issue fixed by @Atharvat, PR merged https://github.com/priyanshux/cryptopy/pull/24
